baseURL = "https://example.com/"
title = "Pandabweer"
enableRobotsTXT = true
theme = ["github.com/onweru/compose"]
enableGitInfo = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]
